### ISSUE TITLE
创建后只有这个脚本本身被记录了，其他的都没有记录

### ISSUE THREAD

**Issue by Joackk** [SiriusXT/trilium-back-to-history#1]
创建了脚本，和存储历史用的笔记后，发现只有这个脚本和几个生效了，其他的笔记都没有被记录进去，这是需要时间来记录还是需要什么操作来触发呢？
![image](https://user-images.githubusercontent.com/45162558/235429986-47bfc1f8-d213-453e-a1ab-9a90b4cf9c49.png)
![image](https://user-images.githubusercontent.com/45162558/235430097-ff3a4f2a-037f-4e36-ad49-746c2d36e58f.png)

**Comment by SiriusXT** [comment]
首先看浏览时滚动条是否加载了，
当最后浏览位置在页面首部时是不显示跳转的，因为默认位置就是开始位置
还不行检查历史记录里有没有当前浏览笔记的记录

**Comment by Joackk** [comment]
> 首先看浏览时滚动条是否加载了， 当最后浏览位置在页面首部时是不显示跳转的，因为默认位置就是开始位置 还不行检查历史记录里有没有当前浏览笔记的记录

是的我就是检查了浏览笔记的记录，浏览了多份笔记后，他都没有进行记录，只有脚本本身、历史记录、还有一个脚本这三个有记录，其他的都没有进行记录

**Comment by Joackk** [comment]
> 首先看浏览时滚动条是否加载了， 当最后浏览位置在页面首部时是不显示跳转的，因为默认位置就是开始位置 还不行检查历史记录里有没有当前浏览笔记的记录

似乎找到问题了，只读模式的不会被记录，只有编辑模式，然后还要进行一个修改的操作才会被记录
